In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
  'employee_id': [101, 102, 103, 104, 105, 106, 107, 102, 108],
  'name': [' Ana Garcia ', 'BOB SMITH', 'Clara_Dupont', 'diego ruiz',
            'Emma Johnson', 'LUCA ROSSI', 'sara chen', 'BOB SMITH', 'Yuki Tanaka'],
  'department': ['Sales', 'sales', 'Tech', 'TECH', 'HR','Hr', 'Tech', 'sales', 'HR'],
  'salary': ['50000', '62000', '75000', 'N/A', '58000',
            '71000', 'N/A', '62000', '66000'],
  'start_date': ['2021-03-01', '2019-07-15', '2020-11-30', '15/04/2022',
                 '2023-01-10', '2018-06-01', '2022-09-20', '2019-07-15', '2020-05-14'],
  'performance': [85, 92, np.nan, 78, 95, np.nan, 88, 92, 71],
  'email': ['ana@company.com', 'bob@company.com', 'clara@company.com',
            'diego@company.com', 'emma@company.com', 'luca@company.com',
            'sara@company.com', 'bob@company.com', 'yuki@company.com']
})
df

,employee_id,name,department,salary,start_date,performance,email
0,101,Ana Garcia,Sales,50000,2021-03-01,85.0,ana@company.com
1,102,BOB SMITH,sales,62000,2019-07-15,92.0,bob@company.com
2,103,Clara_Dupont,Tech,75000,2020-11-30,NaN,clara@company.com
3,104,diego ruiz,TECH,N/A,15/04/2022,78.0,diego@company.com
4,105,Emma Johnson,HR,58000,2023-01-10,95.0,emma@company.com
5,106,LUCA ROSSI,Hr,71000,2018-06-01,NaN,luca@company.com
6,107,sara chen,Tech,N/A,2022-09-20,88.0,sara@company.com
7,102,BOB SMITH,sales,62000,2019-07-15,92.0,bob@company.com
8,108,Yuki Tanaka,HR,66000,2020-05-14,71.0,yuki@company.com

In [14]:
#Challenge 1 — easy
#Run a full audit on the raw dataset before touching anything. 
#Print the number of duplicates, the number of nulls per column, and the data type of each column. 

print(df.info())
print(df.isnull().sum())
print(df.duplicated().sum())

print(df[df.duplicated()])

df = df.drop_duplicates().reset_index(drop=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  9 non-null      int64
 1   name         9 non-null      object
 2   department   9 non-null      object
 3   salary       9 non-null      object
 4   start_date   9 non-null      object
 5   performance  7 non-null      float64
 6   email        9 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 636.0+ bytes
None
employee_id    0
name           0
department     0
salary         0
start_date     0
performance    2
email          0
dtype: int64
1
   employee_id       name department salary  start_date  performance  \
7          102  BOB SMITH      sales  62000  2019-07-15         92.0

             email
7  bob@company.com

In [15]:
df

,employee_id,name,department,salary,start_date,performance,email
0,101,Ana Garcia,Sales,50000,2021-03-01,85.0,ana@company.com
1,102,BOB SMITH,sales,62000,2019-07-15,92.0,bob@company.com
2,103,Clara_Dupont,Tech,75000,2020-11-30,NaN,clara@company.com
3,104,diego ruiz,TECH,N/A,15/04/2022,78.0,diego@company.com
4,105,Emma Johnson,HR,58000,2023-01-10,95.0,emma@company.com
5,106,LUCA ROSSI,Hr,71000,2018-06-01,NaN,luca@company.com
6,107,sara chen,Tech,N/A,2022-09-20,88.0,sara@company.com
7,108,Yuki Tanaka,HR,66000,2020-05-14,71.0,yuki@company.com

In [17]:
#Challenge 2 — medium
#Clean the entire dataset in the correct order: duplicates first, then text, then data types, then dates, then nulls. 
#Print the clean df at the end. Order matters — think about why before you start.

df['name']=df['name'].str.strip()
df['name']=df['name'].str.replace('_',' ')
df['name']=df['name'].str.title()

df['department'] = df['department'].str.strip().str.title()

print(df[['name','department']])

           name department
0    Ana Garcia      Sales
1     Bob Smith      Sales
2  Clara Dupont       Tech
3    Diego Ruiz       Tech
4  Emma Johnson         Hr
5    Luca Rossi         Hr
6     Sara Chen       Tech
7   Yuki Tanaka         Hr

In [18]:
df

,employee_id,name,department,salary,start_date,performance,email
0,101,Ana Garcia,Sales,50000,2021-03-01,85.0,ana@company.com
1,102,Bob Smith,Sales,62000,2019-07-15,92.0,bob@company.com
2,103,Clara Dupont,Tech,75000,2020-11-30,NaN,clara@company.com
3,104,Diego Ruiz,Tech,N/A,15/04/2022,78.0,diego@company.com
4,105,Emma Johnson,Hr,58000,2023-01-10,95.0,emma@company.com
5,106,Luca Rossi,Hr,71000,2018-06-01,NaN,luca@company.com
6,107,Sara Chen,Tech,N/A,2022-09-20,88.0,sara@company.com
7,108,Yuki Tanaka,Hr,66000,2020-05-14,71.0,yuki@company.com

In [21]:
df['department']=df['department'].str.replace('Hr','HR')

In [22]:
df

,employee_id,name,department,salary,start_date,performance,email,deparment
0,101,Ana Garcia,Sales,50000,2021-03-01,85.0,ana@company.com,Sales
1,102,Bob Smith,Sales,62000,2019-07-15,92.0,bob@company.com,Sales
2,103,Clara Dupont,Tech,75000,2020-11-30,NaN,clara@company.com,Tech
3,104,Diego Ruiz,Tech,N/A,15/04/2022,78.0,diego@company.com,Tech
4,105,Emma Johnson,HR,58000,2023-01-10,95.0,emma@company.com,HR
5,106,Luca Rossi,HR,71000,2018-06-01,NaN,luca@company.com,HR
6,107,Sara Chen,Tech,N/A,2022-09-20,88.0,sara@company.com,Tech
7,108,Yuki Tanaka,HR,66000,2020-05-14,71.0,yuki@company.com,HR

In [29]:
#Challenge 3 — hard
#After cleaning: find the average salary and average performance score per department. 
#Which department pays the most? Which performs best? Present both results sorted highest to lowest.

df['salary']=df['salary'].replace('N/A',np.nan)

df['salary']=df['salary'].astype(float)

df['salary']=df.groupby('department')['salary'].transform(
    lambda x: x.fillna(x.mean())
)

df['performance'] = df['performance'].fillna(df['performance'].median())

df

,employee_id,name,department,salary,start_date,performance,email,deparment
0,101,Ana Garcia,Sales,50000.0,2021-03-01,85.0,ana@company.com,Sales
1,102,Bob Smith,Sales,62000.0,2019-07-15,92.0,bob@company.com,Sales
2,103,Clara Dupont,Tech,75000.0,2020-11-30,86.5,clara@company.com,Tech
3,104,Diego Ruiz,Tech,75000.0,15/04/2022,78.0,diego@company.com,Tech
4,105,Emma Johnson,HR,58000.0,2023-01-10,95.0,emma@company.com,HR
5,106,Luca Rossi,HR,71000.0,2018-06-01,86.5,luca@company.com,HR
6,107,Sara Chen,Tech,75000.0,2022-09-20,88.0,sara@company.com,Tech
7,108,Yuki Tanaka,HR,66000.0,2020-05-14,71.0,yuki@company.com,HR

In [30]:
df['start_date'] = pd.to_datetime(df['start_date'], format='mixed', dayfirst=True)
df['start_year'] = df['start_date'].dt.year
df['years_at_company'] = 2024 - df['start_date'].dt.year
print(df[['name', 'start_date', 'years_at_company']])

           name start_date  years_at_company
0    Ana Garcia 2021-03-01                 3
1     Bob Smith 2019-07-15                 5
2  Clara Dupont 2020-11-30                 4
3    Diego Ruiz 2022-04-15                 2
4  Emma Johnson 2023-01-10                 1
5    Luca Rossi 2018-06-01                 6
6     Sara Chen 2022-09-20                 2
7   Yuki Tanaka 2020-05-14                 4

In [31]:
df

,employee_id,name,department,salary,start_date,performance,email,deparment,start_year,years_at_company
0,101,Ana Garcia,Sales,50000.0,2021-03-01,85.0,ana@company.com,Sales,2021,3
1,102,Bob Smith,Sales,62000.0,2019-07-15,92.0,bob@company.com,Sales,2019,5
2,103,Clara Dupont,Tech,75000.0,2020-11-30,86.5,clara@company.com,Tech,2020,4
3,104,Diego Ruiz,Tech,75000.0,2022-04-15,78.0,diego@company.com,Tech,2022,2
4,105,Emma Johnson,HR,58000.0,2023-01-10,95.0,emma@company.com,HR,2023,1
5,106,Luca Rossi,HR,71000.0,2018-06-01,86.5,luca@company.com,HR,2018,6
6,107,Sara Chen,Tech,75000.0,2022-09-20,88.0,sara@company.com,Tech,2022,2
7,108,Yuki Tanaka,HR,66000.0,2020-05-14,71.0,yuki@company.com,HR,2020,4

In [32]:
#Challenge 4 — boss level
#Add a new column called seniority based on years_at_company: less than 2 years = 'Junior', 2 to 4 years = 'Mid', more than 4 years = 'Senior'. 
#Then count how many employees are in each seniority band per department



conditions = [
    df['years_at_company'] < 2,           # Junior
    (df['years_at_company'] >= 2) & (df['years_at_company'] <= 4),  # Mid
    df['years_at_company'] > 4            # Senior
]


choices = ['Junior', 'Mid', 'Senior']


df['seniority'] = np.select(conditions, choices, default='Unknown')


result = df.groupby(['department', 'seniority'])['employee_id'].count()
print(result)

department  seniority
HR          Junior       1
            Mid          1
            Senior       1
Sales       Mid          1
            Senior       1
Tech        Mid          3
Name: employee_id, dtype: int64

In [33]:
df

,employee_id,name,department,salary,start_date,performance,email,deparment,start_year,years_at_company,seniority
0,101,Ana Garcia,Sales,50000.0,2021-03-01,85.0,ana@company.com,Sales,2021,3,Mid
1,102,Bob Smith,Sales,62000.0,2019-07-15,92.0,bob@company.com,Sales,2019,5,Senior
2,103,Clara Dupont,Tech,75000.0,2020-11-30,86.5,clara@company.com,Tech,2020,4,Mid
3,104,Diego Ruiz,Tech,75000.0,2022-04-15,78.0,diego@company.com,Tech,2022,2,Mid
4,105,Emma Johnson,HR,58000.0,2023-01-10,95.0,emma@company.com,HR,2023,1,Junior
5,106,Luca Rossi,HR,71000.0,2018-06-01,86.5,luca@company.com,HR,2018,6,Senior
6,107,Sara Chen,Tech,75000.0,2022-09-20,88.0,sara@company.com,Tech,2022,2,Mid
7,108,Yuki Tanaka,HR,66000.0,2020-05-14,71.0,yuki@company.com,HR,2020,4,Mid